- name: Install System Dependencies & Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick wget fonts-noto-core fonts-sil-scheherazade
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml
          
          # تحميل خط الرسم العثماني بصيغة صحيحة ومباشرة
          wget -q -O uthmanic_font.ttf "https://raw.githubusercontent.com/thetrueready/quran-bot/master/fonts/uthmanic_hafs.ttf"
          
          pip install -r requirements.txt
