- name: Install System Dependencies & Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick fonts-noto-core fonts-sil-scheherazade
          sudo sed -i 's/<policy domain="path" rights="none" pattern="@\*"/<!-- <policy domain="path" rights="none" pattern="@\*" -->/' /etc/ImageMagick-6/policy.xml || true
          sudo sed -i 's/rights="none" pattern="@\*"/rights="read|write" pattern="@\*"/' /etc/ImageMagick-6/policy.xml || true
          # رفع الحدود القصوى لأبعاد الصور والذاكرة لمنع خطأ exceeds limit نهائياً
          sudo sed -i 's/<policy domain="resource" name="width" value=".*"\/>/<policy domain="resource" name="width" value="32KP"\/>/' /etc/ImageMagick-6/policy.xml || true
          sudo sed -i 's/<policy domain="resource" name="height" value=".*"\/>/<policy domain="resource" name="height" value="32KP"\/>/' /etc/ImageMagick-6/policy.xml || true
          sudo sed -i 's/<policy domain="resource" name="area" value=".*"\/>/<policy domain="resource" name="area" value="128MP"\/>/' /etc/ImageMagick-6/policy.xml || true
          sudo sed -i 's/<policy domain="resource" name="memory" value=".*"\/>/<policy domain="resource" name="memory" value="2GiB"\/>/' /etc/ImageMagick-6/policy.xml || true
          pip install --upgrade pip
          pip install "moviepy==1.0.3" "Pillow<10.0.0" python-telegram-bot groq requests arabic-reshaper python-bidi
